AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Simple template containign'
Resources:
  mehfBuildkiteCDTestLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'skytest.handler'
      Runtime: 'nodejs10.x'
      Description: 'Simple test lambda.'
      MemorySize: 1024
      Timeout: 15
      Role: 'arn:aws:iam::141700968474:role/rolerequirement-dev-lambda-iam'